//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FmDraft
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formations
    {
        public int Id { get; set; }
        public string For1 { get; set; }
        public string For2 { get; set; }
        public string For3 { get; set; }
        public string For4 { get; set; }
        public string For5 { get; set; }
        public string For6 { get; set; }
        public string For7 { get; set; }
        public string For8 { get; set; }
        public string For9 { get; set; }
        public string For10 { get; set; }
        public string For11 { get; set; }
        public string ForTitle { get; set; }
    }
}
