//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FmDraft
{
    using System;
    using System.Collections.Generic;
    
    public partial class Players
    {
        public int ID_Player { get; set; }
        public string Name { get; set; }
        public string Nationality { get; set; }
        public Nullable<int> FK_Club { get; set; }
        public Nullable<byte> Acceleration { get; set; }
        public Nullable<byte> Workrate { get; set; }
        public Nullable<byte> Vision { get; set; }
        public Nullable<byte> Thowing { get; set; }
        public Nullable<byte> Tendency_to_punch_ball { get; set; }
        public Nullable<byte> Technique { get; set; }
        public Nullable<byte> Teamwork { get; set; }
        public Nullable<byte> Tackling { get; set; }
        public Nullable<byte> Strentgh { get; set; }
        public Nullable<byte> Stamina { get; set; }
        public Nullable<byte> Rushing_out { get; set; }
        public Nullable<byte> Reflexes { get; set; }
        public Nullable<byte> Positioning { get; set; }
        public Nullable<byte> Pentalty_kick { get; set; }
        public Nullable<byte> Passing { get; set; }
        public Nullable<byte> Pace { get; set; }
        public Nullable<byte> One_on_one { get; set; }
        public Nullable<byte> Off_the_ball { get; set; }
        public Nullable<byte> Natural_fitness { get; set; }
        public Nullable<byte> Marking { get; set; }
        public Nullable<byte> Long_throw { get; set; }
        public Nullable<byte> Longshot { get; set; }
        public Nullable<byte> Leadership { get; set; }
        public Nullable<byte> Kicking { get; set; }
        public Nullable<byte> Jumping { get; set; }
        public Nullable<byte> Heading { get; set; }
        public Nullable<byte> Handling { get; set; }
        public Nullable<byte> Free_kick { get; set; }
        public Nullable<byte> Flair { get; set; }
        public Nullable<byte> First_touch { get; set; }
        public Nullable<byte> Finishing { get; set; }
        public Nullable<byte> Eccentricity { get; set; }
        public Nullable<byte> Dribbling { get; set; }
        public Nullable<byte> Determination { get; set; }
        public Nullable<byte> Decisions { get; set; }
        public Nullable<byte> Crossing { get; set; }
        public Nullable<byte> Corner_kick { get; set; }
        public Nullable<byte> Concentration { get; set; }
        public Nullable<byte> Composure { get; set; }
        public Nullable<byte> Communication { get; set; }
        public Nullable<byte> Command_of_area { get; set; }
        public Nullable<byte> Bravery { get; set; }
        public Nullable<byte> Balance { get; set; }
        public Nullable<byte> Anticipation { get; set; }
        public Nullable<byte> Agility { get; set; }
        public Nullable<byte> Aggression { get; set; }
        public Nullable<byte> Aerial { get; set; }
        public string Value { get; set; }
        public string Position { get; set; }
        public Nullable<byte> Age { get; set; }
        public Nullable<int> Hight { get; set; }
        public Nullable<byte> Weight { get; set; }
    
        public virtual Clubs Clubs { get; set; }
    }
}
