//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FmDraft
{
    using System;
    using System.Collections.Generic;
    
    public partial class Players
    {
        public int ID_Player { get; set; }
        public string Name { get; set; }
        public string Nationality { get; set; }
        public int FK_Club { get; set; }
        public byte Acceleration { get; set; }
        public byte Workrate { get; set; }
        public byte Vision { get; set; }
        public byte Thowing { get; set; }
        public byte Tendency_to_punch_ball { get; set; }
        public byte Technique { get; set; }
        public byte Teamwork { get; set; }
        public byte Tackling { get; set; }
        public byte Strentgh { get; set; }
        public byte Stamina { get; set; }
        public byte Rushing_out { get; set; }
        public byte Reflexes { get; set; }
        public byte Positioning { get; set; }
        public byte Pentalty_kick { get; set; }
        public byte Passing { get; set; }
        public byte Pace { get; set; }
        public byte One_on_one { get; set; }
        public byte Off_the_ball { get; set; }
        public byte Natural_fitness { get; set; }
        public byte Marking { get; set; }
        public byte Long_throw { get; set; }
        public byte Longshot { get; set; }
        public byte Leadership { get; set; }
        public byte Kicking { get; set; }
        public byte Jumping { get; set; }
        public byte Heading { get; set; }
        public byte Handling { get; set; }
        public byte Free_kick { get; set; }
        public byte Flair { get; set; }
        public byte First_touch { get; set; }
        public byte Finishing { get; set; }
        public byte Eccentricity { get; set; }
        public byte Dribbling { get; set; }
        public byte Determination { get; set; }
        public byte Decisions { get; set; }
        public byte Crossing { get; set; }
        public byte Corner_kick { get; set; }
        public byte Concentration { get; set; }
        public byte Composure { get; set; }
        public byte Communication { get; set; }
        public byte Command_of_area { get; set; }
        public byte Bravery { get; set; }
        public byte Balance { get; set; }
        public byte Anticipation { get; set; }
        public byte Agility { get; set; }
        public byte Aggression { get; set; }
        public byte Aerial { get; set; }
        public string Value { get; set; }
        public string Position { get; set; }
        public byte Age { get; set; }
        public int Hight { get; set; }
        public byte Weight { get; set; }
    
        public virtual Clubs Clubs { get; set; }
    }
}
